### ISSUE TITLE
decorators assume request has request.role

### ISSUE THREAD

**Issue by dmyung** [dimagi/django-prbac#24]
It looks like out of the box standalone use of the prbac decorators for requires_permission assumes a middleware is populating request.role.

Commcare-hq has its own middleware for this, but prbac doesn't:
https://github.com/dimagi/commcare-hq/blob/5842708201662d83c23357a3f4db83efb7aa35c4/corehq/apps/domain/middleware.py

Was prbac meant to have its own middleware added for this use?

**Comment by czue** [comment]
hi @dmyung! that sounds right to me.

**Comment by NoahCarnahan** [comment]
@dmyung @czue 
It looks like the hq middleware populates the `request.role` based on the `request.domain`. But since domain is an HQ specific concept, what were you thinking a django-prbac middleware would use to populate the `request.role`?

Another thing is that `has_privilege()`, checks if `request.role` has the privilege, and if it does not, it checks if `request.user.prbac_role` has the privilege, but if `request` doesn't have a `role` attribute at all, it returns `False` right away without checking the user. It seems like perhaps a better approach would be to check the user even if the request doesn't have a role attribute. This might eliminate the need for a middleware?

**Comment by millerdev** [comment]
> It seems like perhaps a better approach would be to check the user even if the request doesn't have a role attribute. This might eliminate the need for a middleware?

I agree with this.
